# “Git push -f” или после нас хоть потоп

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [34]:
def share_bread(N, K):
    # your code here
    return K // N, K % N


# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [35]:
def leap_year(year):
    is_leap = year % 4 == 0 and year % 100 != 0 or year % 400 == 0
    if is_leap:
        return 'YOU SHALL PASS'
    else:
        return 'YOU SHALL NOT PASS'


assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [36]:
def amulet_area(a, b, c):
    p = (a + b + c) / 2
    S = (p * (p - a) * (p - b) * (p - c)) ** 0.5
    # your code here
    return S


assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [39]:
def cal_euclidean(a, b):
    distance = 0
    for ai, bi in zip(a, b):
        distance = distance + (ai - bi) ** 2
    return distance ** 0.5


def cal_manhattan(a, b):
    distance = 0
    for ai, bi in zip(a, b):
        distance = distance + abs(ai - bi)
    return distance


def cal_cosine(a, b):
    ab_sum = 0
    a2_sum = 0
    b2_sum = 0
    for ai, bi in zip(a, b):
        ab_sum = ab_sum + ai * bi
        a2_sum = a2_sum + ai ** 2
        b2_sum = b2_sum + bi ** 2
    return 1 - ab_sum / ((a2_sum ** 0.5) * (b2_sum ** 0.5))

In [40]:
import numpy as np

a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

31.0322412983658
85
-0.3184779557607272


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [71]:
def normalize(a):
    min_val = None
    min_i = []
    max_val = None
    max_i = []
    for i, ai in enumerate(a):
        if ai == min_val:
            min_i.append(i)
        if ai == max_val:
            max_i.append(i)
        if min_val is None or ai < min_val:
            min_val = ai
            min_i = [i]
        if max_val is None or ai > max_val:
            max_val = ai
            max_i = [i]
    for i in min_i:
        a[i] = 0
    for i in max_i:
        a[i] = 1


my_array = np.random.rand(100)
normalize(my_array)
print(np.max(my_array), np.min(my_array))
print(my_array)

0.9988332078727415 0.005372960901346424
1.0 0.0
[0.0638543  0.99048755 0.61783838 0.46742167 0.30691908 0.18135309
 0.01932009 0.65598565 0.78680017 0.95348378 0.61758179 0.39400966
 0.30217838 0.672776   0.39624296 0.15196205 0.67820635 0.49160134
 0.26453874 0.4965     0.89044254 0.         0.80219993 0.7733072
 0.74876889 0.645781   0.3729773  0.5715455  0.99090684 0.2921113
 0.30467573 0.59555529 0.38721738 0.30894427 0.18294744 0.57045732
 0.72734068 0.39128428 0.72945702 0.2650769  0.16628086 0.60537345
 0.21948583 0.04925898 0.28034713 0.47606533 1.         0.22362312
 0.78315636 0.08647078 0.60560161 0.99206691 0.66583758 0.62951411
 0.79739808 0.44754405 0.66269134 0.66046454 0.41397341 0.95023022
 0.1624531  0.12984423 0.8395452  0.48803416 0.02791624 0.61916525
 0.63125426 0.56858473 0.26257386 0.50300377 0.38369482 0.47393278
 0.98816621 0.21738986 0.79329917 0.30393939 0.92237753 0.20312019
 0.23037051 0.81437764 0.81274113 0.98299164 0.163452   0.45979477
 0.97554018 0.41

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [83]:
def get_max_column_number(array):
    max_value = None
    max_col = None
    for row_i, row in enumerate(array):
        for col_i, value in enumerate(row):
            if max_value is None or value > max_value:
                max_value = value
                max_col = col_i
    return max_col

def get_column(array, col_number):
    column=[]
    for row in array:
        column.append(int(row[col_number]))
    return column

my_array = np.random.randint(0, 51, size=(5, 6))
print('Shape: ', my_array.shape)
print('Array')
print(my_array)

selected_column_number = get_max_column_number(my_array)
print('Column_number: ', selected_column_number)

selected_column = get_column(my_array, selected_column_number)
print(selected_column)

Shape:  (5, 6)
Array
[[ 3  4 41 21 50 15]
 [ 0 35  0 44  2  9]
 [47  9  6  7  9 15]
 [10 19 36 44 32 28]
 [45 32 34 31  6 44]]
Column_number:  4
[50, 2, 9, 32, 6]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [88]:
def get_unique_rows(X):
      seen = set()
      unique_rows = []
      for row in X:
          row_tuple = tuple(int(x) for x in row)
          if row_tuple not in seen:
              seen.add(row_tuple)
              unique_rows.append(list(row_tuple))
      return unique_rows

X = np.random.randint(4, 6, size=(10, 3))
print(X)

unique_rows = get_unique_rows(X)
print(unique_rows)

[[5 5 5]
 [4 5 4]
 [4 4 5]
 [5 4 5]
 [4 4 5]
 [4 5 4]
 [4 5 4]
 [5 5 4]
 [4 4 4]
 [5 4 5]]
[[5, 5, 5], [4, 5, 4], [4, 4, 5], [5, 4, 5], [5, 5, 4], [4, 4, 4]]
